# Generated by Django 5.1.6 on 2025-02-20 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('item_id', models.CharField(default='', max_length=24)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
