# Generated by Django 5.1.6 on 2025-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.UUIDField(null=True),
        ),
    ]
